cpufreq_times: add missing header
../drivers/cpufreq/cpufreq_times.c:369:17: error: implicit declaration of
      function 'struct_size' [-Werror,-Wimplicit-function-declaration]
        tmp =  kzalloc(struct_size(freqs, freq_table, count), GFP_KERNEL);
                       ^
../drivers/cpufreq/cpufreq_times.c:369:17: error: this function declaration is
      not a prototype [-Werror,-Wstrict-prototypes]

Signed-off-by: Yaroslav Furman <yaro330@gmail.com>